#!/usr/bin/env bash

##
## Runs the docker-credential-gcloud in a a container
##

set -eu

SDS_GCLOUD_CONTAINER_NAME="sds-gcloud-auth"
docker exec -i \
     ${SDS_GCLOUD_CONTAINER_NAME} \
     gcloud auth docker-helper "$@"