#!/usr/bin/env bash

##
## printf_color
##
## A simple script to print colored text
##
## Usage:
##   printf_color <color> <text>
##
## Args:
##   <color> : The color to use
##   <text>  : The text to print
##
## Returns:
##   None
##
## Example:
##   printf_color red "Hello World"
##
## Notes:
##   The color must be one of the following:
##     - red
##     - green
##     - yellow
##     - blue
##
##   The script will print the text in the specified color and reset the color
##   to default.
##
set -o errexit
set -o pipefail
set -o nounset

color_name="${1}"
case "${color_name}" in
	'red')
		color_prefix='\e[1;31m'
		;;
	'green')
		color_prefix='\e[1;32m'
		;;
	'yellow')
		color_prefix='\e[1;33m'
		;;
	'blue')
		color_prefix='\e[1;34m'
		;;
	*)
		>&2 printf 'INVALID COLOR: ${color_name}\n'
esac
shift
printf "${color_prefix}%b\e[0m" "${@}"
