#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

color_name="${1}"
case "${color_name}" in
	'red')
		color_prefix='\e[1;31m'
		;;
	'green')
		color_prefix='\e[1;32m'
		;;
	'yellow')
		color_prefix='\e[1;33m'
		;;
	'blue')
		color_prefix='\e[1;34m'
		;;
	*)
		>&2 printf 'INVALID COLOR: ${color_name}\n'
esac
shift
printf "${color_prefix}%b\e[0m" "${@}"
